kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: sleep-job
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sleepy
            image: alpine
            command: ['sleep', '300']
          restartPolicy: OnFailure

