apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proxy
  name: nginx-lab7
spec:
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - image: nginx:1.9
        name: nginx
      dnsPolicy: ClusterFirst
      restartPolicy: Always
status: {}
